apiVersion: v1
kind: Secret
metadata:
  name: myntra-agent-secrets
type: Opaque
stringData:
  DATABASE_URL: "postgresql://admin:secret@postgres-service:5432/myntra_agent"
  REDIS_URL: "redis://redis-service:6379"
  RABBITMQ_URL: "amqp://admin:secret@rabbitmq-service:5672"
  GROQ_API_KEY: "your_groq_api_key_here"
  JWT_SECRET: "prod_jwt_secret_min_32_chars_long_key"
  WEBHOOK_SECRET: "prod_webhook_secret_key"
